Repository hackers-ignite-open-source-community/FrontendMentor, pull requests merged in 2023-10, with the labels that each got.

#3 Frontend Mentor - News Homepage using CSS
  Responsive-News-Homepage-famanakis/.gitignore
  Responsive-News-Homepage-famanakis/README.md
  Responsive-News-Homepage-famanakis/design/README.md
  Responsive-News-Homepage-famanakis/design/active-states.jpg
  Responsive-News-Homepage-famanakis/design/desktop-design.jpg
  Responsive-News-Homepage-famanakis/design/desktop-preview.jpg
  Responsive-News-Homepage-famanakis/design/mobile-design.jpg
  Responsive-News-Homepage-famanakis/design/mobile-menu.jpg
  Responsive-News-Homepage-famanakis/design/style-guide.md
  Responsive-News-Homepage-famanakis/index.html
  Responsive-News-Homepage-famanakis/src/assets/fonts/Inter-VariableFont_slnt,wght.ttf
  Responsive-News-Homepage-famanakis/src/assets/fonts/README.txt
  Responsive-News-Homepage-famanakis/src/assets/fonts/static/Inter-Bold.ttf
  Responsive-News-Homepage-famanakis/src/assets/fonts/static/Inter-ExtraBold.ttf
  Responsive-News-Homepage-famanakis/src/assets/fonts/static/Inter-Regular.ttf
  Responsive-News-Homepage-famanakis/src/assets/images/favicon-32x32.png
  Responsive-News-Homepage-famanakis/src/assets/images/icon-menu-close.svg
  Responsive-News-Homepage-famanakis/src/assets/images/icon-menu.svg
  Responsive-News-Homepage-famanakis/src/assets/images/image-gaming-growth.jpg
  Responsive-News-Homepage-famanakis/src/assets/images/image-retro-pcs.jpg
  Responsive-News-Homepage-famanakis/src/assets/images/image-top-laptops.jpg
  Responsive-News-Homepage-famanakis/src/assets/images/image-web-3-desktop.jpg
  Responsive-News-Homepage-famanakis/src/assets/images/image-web-3-mobile.jpg
  Responsive-News-Homepage-famanakis/src/assets/images/logo.svg
  Responsive-News-Homepage-famanakis/src/assets/images/mobile-nav.png
  Responsive-News-Homepage-famanakis/src/assets/images/mobile.png
  Responsive-News-Homepage-famanakis/src/index.js
  Responsive-News-Homepage-famanakis/src/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#4 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted, hacktoberfest

#7 add: result summary component solution
  CONTRIBUTORS.md
  results-summary-component-bishwobista/.gitignore
  results-summary-component-bishwobista/README-template.md
  results-summary-component-bishwobista/README.md
  results-summary-component-bishwobista/assets/fonts/HankenGrotesk-VariableFont_wght.ttf
  results-summary-component-bishwobista/assets/fonts/README.txt
  results-summary-component-bishwobista/assets/fonts/static/HankenGrotesk-Bold.ttf
  results-summary-component-bishwobista/assets/fonts/static/HankenGrotesk-ExtraBold.ttf
  results-summary-component-bishwobista/assets/fonts/static/HankenGrotesk-Medium.ttf
  results-summary-component-bishwobista/assets/images/favicon-32x32.png
  results-summary-component-bishwobista/assets/images/icon-memory.svg
  results-summary-component-bishwobista/assets/images/icon-reaction.svg
  results-summary-component-bishwobista/assets/images/icon-verbal.svg
  results-summary-component-bishwobista/assets/images/icon-visual.svg
  results-summary-component-bishwobista/data.json
  results-summary-component-bishwobista/design/active-states.jpg
  results-summary-component-bishwobista/design/desktop-design.jpg
  results-summary-component-bishwobista/design/desktop-preview.jpg
  results-summary-component-bishwobista/design/mobile-design.jpg
  results-summary-component-bishwobista/index.html
  results-summary-component-bishwobista/style-guide.md
  results-summary-component-bishwobista/style.css
Labels: hacktoberfest

#9 Added QR code component - Frontend Mentor Challenge MaySi11
  CONTRIBUTORS.md
  qr-code-component-maysi11/images/favicon-32x32.png
  qr-code-component-maysi11/images/image-qr-code.png
  qr-code-component-maysi11/index.html
  qr-code-component-maysi11/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#11 Qr code component ajay
  CONTRIBUTORS.md
  QR-code-component-Ajay/.gitignore
  QR-code-component-Ajay/README.md
  QR-code-component-Ajay/design/desktop-design.jpg
  QR-code-component-Ajay/design/desktop-preview.jpg
  QR-code-component-Ajay/design/mobile-design.jpg
  QR-code-component-Ajay/images/Screenshot.jpg
  QR-code-component-Ajay/images/favicon-32x32.png
  QR-code-component-Ajay/images/image-qr-code.png
  QR-code-component-Ajay/index.html
  QR-code-component-Ajay/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#13 Interactive card details form sameer bakshi
  CONTRIBUTORS.md
  InteractiveCardDetailsForm--SameerBakshi/.gitignore
  InteractiveCardDetailsForm--SameerBakshi/README.md
  InteractiveCardDetailsForm--SameerBakshi/images/bg-card-back.png
  InteractiveCardDetailsForm--SameerBakshi/images/bg-card-front.png
  InteractiveCardDetailsForm--SameerBakshi/images/bg-main-desktop.png
  InteractiveCardDetailsForm--SameerBakshi/images/bg-main-mobile.png
  InteractiveCardDetailsForm--SameerBakshi/images/card-logo.svg
  InteractiveCardDetailsForm--SameerBakshi/images/favicon-32x32.png
  InteractiveCardDetailsForm--SameerBakshi/images/icon-complete.svg
  InteractiveCardDetailsForm--SameerBakshi/index.html
  InteractiveCardDetailsForm--SameerBakshi/script.js
  InteractiveCardDetailsForm--SameerBakshi/style.css
Labels: hacktoberfest-accepted

#15 Added 3-Column preview card component - Frontend Mentor Challenge MaySi11
  3-column-preview-card-component-maysi11/images/favicon-32x32.png
  3-column-preview-card-component-maysi11/images/icon-luxury.svg
  3-column-preview-card-component-maysi11/images/icon-sedans.svg
  3-column-preview-card-component-maysi11/images/icon-suvs.svg
  3-column-preview-card-component-maysi11/index.html
  3-column-preview-card-component-maysi11/styles.css
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#16 Done with challenge - Newsletter sign-up form with success message
  CONTRIBUTORS.md
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/.eslintrc.cjs
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/.gitignore
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/README.md
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/index.html
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/package-lock.json
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/package.json
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/postcss.config.js
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/public/Thumbs.db
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/public/favicon-32x32.png
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/public/illustration desktop.svg
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/public/illustration mobile.svg
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/public/thumbnail-1.png
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/public/thumbnail-2.png
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/src/App.jsx
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/src/assets/react.svg
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/src/components/Offer.jsx
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/src/components/Subscribe.jsx
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/src/components/SuccessMessage.jsx
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/src/index.css
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/src/main.jsx
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/tailwind.config.js
  Newsletter-sign-up-form-with-success-message-Adufe-Obanijesu/vite.config.js
Labels: hacktoberfest-accepted

#19 Order summary component
  CONTRIBUTORS.md
  order-summary-component-Adufe-Obanijesu/.eslintrc.cjs
  order-summary-component-Adufe-Obanijesu/.gitignore
  order-summary-component-Adufe-Obanijesu/README.md
  order-summary-component-Adufe-Obanijesu/index.html
  order-summary-component-Adufe-Obanijesu/package-lock.json
  order-summary-component-Adufe-Obanijesu/package.json
  order-summary-component-Adufe-Obanijesu/postcss.config.js
  order-summary-component-Adufe-Obanijesu/public/Thumbs.db
  order-summary-component-Adufe-Obanijesu/public/favicon-32x32.png
  order-summary-component-Adufe-Obanijesu/public/icon-music.svg
  order-summary-component-Adufe-Obanijesu/public/illustration-hero.svg
  order-summary-component-Adufe-Obanijesu/public/pattern-background-desktop.svg
  order-summary-component-Adufe-Obanijesu/public/pattern-background-mobile.svg
  order-summary-component-Adufe-Obanijesu/public/thumbnail.png
  order-summary-component-Adufe-Obanijesu/src/App.jsx
  order-summary-component-Adufe-Obanijesu/src/assets/react.svg
  order-summary-component-Adufe-Obanijesu/src/components/Offer.jsx
  order-summary-component-Adufe-Obanijesu/src/components/Subscribe.jsx
  order-summary-component-Adufe-Obanijesu/src/components/SuccessMessage.jsx
  order-summary-component-Adufe-Obanijesu/src/index.css
  order-summary-component-Adufe-Obanijesu/src/main.jsx
  order-summary-component-Adufe-Obanijesu/tailwind.config.js
  order-summary-component-Adufe-Obanijesu/vite.config.js
Labels: hacktoberfest-accepted

#18 Adding a video demo on how to contribute to the repo
  README.md
Labels: hacktoberfest-accepted
